apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc1
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc1-test
spec:
  storageClassName: da-mlops-prod-storageclass-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
