---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: aws-loadbalancer
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::092744370500:role/aws-load-balancer-controller