# create service account policy

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::092744370500:role/node-group-2-eks-node-group-20240630055633841600000005